#!/bin/bash

# Change default timezone to MSK
echo 'timezone: Europe/Helsinki'  >> /etc/cloud/cloud.cfg.d/50_timezone.cfg

# Add the Openstack datasource 
echo 'datasource_list: [OpenStack]'      >> /etc/cloud/cloud.cfg.d/40_datasource.cfg

# Allow centos user to login
sed -i 's/name: centos/name: cloud-user/g' /etc/cloud/cloud.cfg

# Add system build date
DATE=$(date '+%Y-%m-%d')
echo "This system was built on" $DATE >> /etc/motd

# Blacklist floppy
echo 'blacklist floppy' > /etc/modprobe.d/floppy.conf



